import PDFDocument from 'pdfkit';

export function createReportPdfBuffer(report: {
  sampleId: number;
  customer: string;
  fabric: string;
  tests: string[];
  results?: Record<string, string | number>;
  conclusion: string;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ margin: 50 });

    doc.info.Title = `TexLab Report ${report.sampleId}`;
    doc.info.Author = 'TexLab Instruments';
    doc.info.Subject = 'Textile Laboratory Test Report';

    doc.on('data', (chunk) => chunks.push(chunk as Buffer));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('TexLab Instruments', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(14).text('Textile Laboratory Test Report', { align: 'center' });
    doc.moveDown(1.5);

    doc.fontSize(11);
    doc.text(`Report No: RPT-${report.sampleId}`);
    doc.text(`Customer: ${report.customer}`);
    doc.text(`Fabric Type: ${report.fabric}`);
    doc.text(`Conclusion: ${report.conclusion}`);
    doc.moveDown();

    doc.fontSize(13).text('Requested Tests');
    doc.moveDown(0.5);
    report.tests.forEach((test) => doc.fontSize(11).text(`- ${test}`));
    doc.moveDown();

    doc.fontSize(13).text('Results');
    doc.moveDown(0.5);
    const resultEntries = Object.entries(report.results || {});
    if (!resultEntries.length) {
      doc.fontSize(11).text('- Pending result entry');
    } else {
      resultEntries.forEach(([key, value]) => {
        doc.fontSize(11).text(`- ${key}: ${value}`);
      });
    }

    doc.moveDown();
    doc.fontSize(10).text('Generated by TexLab 17025 LAB + SALES SYSTEM');

    doc.end();
  });
}

export function createOfferPdfBuffer(offer: {
  id: number;
  sampleId: number;
  customer: string;
  device: string;
  price: string;
  currency: string;
  validUntil: string;
  status: string;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ margin: 50 });

    doc.info.Title = `TexLab Offer ${offer.id}`;
    doc.info.Author = 'TexLab Instruments';
    doc.info.Subject = 'Commercial Offer';

    doc.on('data', (chunk) => chunks.push(chunk as Buffer));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('TexLab Instruments', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(14).text('Commercial Offer', { align: 'center' });
    doc.moveDown(1.5);

    doc.fontSize(11);
    doc.text(`Offer No: OFF-${offer.id}`);
    doc.text(`Customer: ${offer.customer}`);
    doc.text(`Related Sample ID: ${offer.sampleId}`);
    doc.text(`Device: ${offer.device}`);
    doc.text(`Price: ${offer.price} ${offer.currency}`);
    doc.text(`Valid Until: ${offer.validUntil}`);
    doc.text(`Status: ${offer.status}`);
    doc.moveDown();

    doc.fontSize(12).text('Commercial Note');
    doc.moveDown(0.5);
    doc.fontSize(11).text('This offer was generated from the TexLab lab-to-sales workflow.');
    doc.text('For technical clarifications and delivery planning, contact TexLab Instruments.');
    doc.moveDown();

    doc.fontSize(10).text('Generated by TexLab 17025 LAB + SALES SYSTEM');

    doc.end();
  });
}
